### ISSUE TITLE
Verzeichnisse falsch benamt

### ISSUE THREAD

**Issue by funnyflowerpot** [CTreffOS/codingchaos#144]
Sehr coole Aktion!
Auf Empfehlung mach ich ein Issue auf. Ich hab versehentlich Verzeichnisse mit dem Namen meines RZ-Logins (sriegl) statt meinem Github-Logins (funnyflowerpot). Könntet Ihr das bitte ändern? Vielen Dank!

**Comment by jsaalfeld** [comment]
Werden wir beim Auswerten berücksichtigen.
